version: '3'

services:
  ui:
    container_name: ui
    stdin_open: true
    build: ./client
    ports:
      - '3000:3000'
    networks: 
      - 'realdeal_network'

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks: 
      - 'realdeal_network'
  
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbit
    environment: 
      - RABBITMQ_PASSWORD=password
    networks: 
      - 'realdeal_network'

  api:
    build: ./api
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks: 
      - 'realdeal_network'    

  mongo:
    image: mongo
    restart: always
    command: --serviceExecutor adaptive
    container_name: mongo
    env_file:
        - .env
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: realdeal_read
    volumes:
      - storage:/data/db
    ports:
      - '27017:27017'
    networks: 
      - 'realdeal_network'

volumes:
  storage:
networks: 
  realdeal_network:
    driver: bridge