version: '3'

services:
  db:
    container_name: myqsl
    image: mysql:8
    networks:
        - realdeal
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_ROOT_USER: root
        MYSQL_USER: realdeal
        MYSQL_PASSWORD: passwd
        MYSQL_DATABASE: real_deal
    volumes:
      - 'mysqldata:/var/lib/mysql'
    ports:
    - 3306:3306

  # nginx bedzie reverse-proxy dla frontendu jak i backendu
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    restart: on-failure
    networks:
        - realdeal
    volumes:
      - './server:/usr/src/app'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - './docker/nginx/certbot/conf:/etc/letsencrypt'

  php:
    container_name: php
    user: 1000:1000
    networks:
        - realdeal
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - WITH_XDEBUG=true
    restart: on-failure
    volumes:
      - './server:/usr/src/app:rw'
    env_file:
      - .env

  blackfire:
    image: blackfire/blackfire
    ports:
      - 8707:8707
    environment:
      BLACKFIRE_SERVER_ID: ~
      BLACKFIRE_SERVER_TOKEN: ~
      BLACKFIRE_CLIENT_ID: ~
      BLACKFIRE_CLIENT_TOKEN: ~

  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbit
    networks:
        - realdeal
    environment:
      - RABBITMQ_PASSWORD=password

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
      container_name: elasticsearch
      restart: on-failure
      networks:
        - realdeal
      volumes:
        - esdata:/usr/share/elasticsearch/data
      environment:
        - cluster.name=realdeal_cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - '9200:9200'

networks:
  #default:
  #  external:
  #    name: realdeal
  realdeal:

volumes:
  storage:
    driver: local
  mysqldata:
    driver: local
  esdata:
    driver: local
