version: '3'

services:
  ui:
    container_name: ui
    stdin_open: true
    volumes:
      - './client:/app:rw'
    build: ./client
    ports:
      - '3000:3000'

  db:
    container_name: myqsl
    image: mysql:5.7
    networks:
        - realdeal
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_USER: root
        MYSQL_PASSWORD: passwd
        MYSQL_DATABASE: real_deal
    volumes:
      - 'mysqldata:/var/lib/mysql'
    ports:
    - 3306:3306

  nginx:
    image: nginx:1.15.3-alpine
    container_name: nginx
    restart: on-failure
    networks:
        - realdeal
    volumes:
      - './server:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - certs:/etc/letsencrypt # certificates
      - certs_data:/data/letsencrypt #certificate data
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - './docker/nginx/certbot/conf:/etc/letsencrypt'

  php:
    container_name: php
    user: 1000:1000
    networks:
        - realdeal
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './server:/usr/src/app:rw'
    env_file:
      - .env

  blackfire:
    image: blackfire/blackfire
    ports:
      - 8707:8707
    environment:
      BLACKFIRE_SERVER_ID: ~
      BLACKFIRE_SERVER_TOKEN: ~
      BLACKFIRE_CLIENT_ID: ~
      BLACKFIRE_CLIENT_TOKEN: ~

  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbit
    networks:
        - realdeal
    environment:
      - RABBITMQ_PASSWORD=password

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
      container_name: elasticsearch
      restart: on-failure
      networks:
        - realdeal
      volumes:
        - esdata:/usr/share/elasticsearch/data
      environment:
        - cluster.name=realdeal_cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS--Xms4g-Xmx4g"
        - discovery.type=single-node
      ulimits:
        nproc: 3000
        nofile: 65536
        memlock:
          soft: -1
          hard: -1
      ports:
        - '9200:9200'

networks:
  realdeal:
    driver: bridge # configure bridge network

volumes:
  storage:
    driver: local
  mysqldata:
    driver: local
  esdata:
    driver: local
  certs:
    driver: local
  certs_data:
    driver: local
