version: '3'

services:
  ui:
    container_name: ui
    stdin_open: true
    volumes:
      - './client:/app:rw'
    build: ./client
    ports:
      - '3000:3000'

  db:
    container_name: myqsl
    image: mysql:5.7
    restart: on-failure
    environment:
        MYSQL_ROOT_PASSWORD: passwd
        MYSQL_USER: root
        MYSQL_PASSWORD: passwd
        MYSQL_DATABASE: real_deal
    volumes:
      - 'mysqldata:/var/lib/mysql'
    ports:
    - 3306:3306
    
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './server:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 8080:80
    depends_on:
      - php
  
  php:
    container_name: php
    user: 1000:1000
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './server:/usr/src/app'
    env_file:
      - .env
      
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbit
    environment: 
      - RABBITMQ_PASSWORD=password

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
      container_name: elasticsearch
      volumes:
        - esdata:/usr/share/elasticsearch/data
      environment:
        - cluster.name=realdeal_cluster
       # - include_type_name=true
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS--Xms4g-Xmx4g"
        - discovery.type=single-node
      ulimits:
        nproc: 3000
        nofile: 65536
        memlock:
          soft: -1
          hard: -1
      ports:
        - '9200:9200'

volumes:
  storage:
    driver: local
  mysqldata:
    driver: local
  esdata:
    driver: local  