api_platform:
    doctrine: 
        enabled: true
    mapping:
        paths: ['%kernel.project_dir%/src/SalesManagement/Domain/Offer']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    oauth:
        enabled: true    
