doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '5.7'
        dbname: real_deal
        user: root
        password: passwd

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            SalesManagement:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SalesManagement/Domain/'
                prefix: 'RealDeal\SalesManagement'
            ContractManagement:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/ContractManagement/Domain/'
                prefix: 'RealDeal\ContractManagement'

