# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    serializer:
        serializer: realdeal.serializer
    clients:
        default:
            url: '%env(ELASTICSEARCH_URL)%'
            username: elastic
            password: changeme
    indexes:
        sales_management:
            index_name: sales_management_%kernel.environment%
            types:
                customers:
                    persistence:
                        driver: orm
                        model: RealDeal\SalesManagement\Domain\Client\Client
                        provider: ~
                        finder: ~
                    properties:
                        id: ~
                        name: ~
                        secondName: ~
                        email: ~
                        stage: ~
                        ownedProperties: ~
                offers:
                    persistence:
                        driver: orm
                        model: RealDeal\SalesManagement\Domain\Offer\Offer
                        provider: ~
                        finder: ~
                    properties:
                        id: ~
                        identifier: ~
                        name: ~
                        propertyType: ~
                        offeringType: ~



