<?php

declare(strict_types=1);

namespace RealDeal\Tests\AccountManagement\Unit;

use PHPUnit\Framework\TestCase;

class CreateNewUserRequestValidator extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
