#index:
#    path: /
#    controller: App\Controller\DefaultController::index

## SalesManagement Routing

##### Offers Routes

salesManagement.getAllOffers:
  methods: ['GET']
  path: offers/all
  controller: SalesManagement.OfferController::getAllOffersAction

salesManagement.addOffer:
  methods: ['POST']
  path: offers/add
  controller: SalesManagement.OfferController::addOfferAction

salesManagement.getSingleOffer:
  methods: ['GET']
  path: offers/{id}
  controller: SalesManagement.OfferController::getSingleOfferAction

##### Client routes

salesManagement.addClient:
  methods: ['POST']
  path: clients/add
  controller: SalesManagement.ClientController::addClientAction

salesManagement.addProspectiveProperties:
  methods: ['POST']
  path: clients/{clientId}/prospectiveProperties/add
  controller: SalesManagement.ClientController::addProspectivePropertyToClientAction

salesManagement.getClient:
  methods: ['GET']
  path: clients/{id}
  controller: SalesManagement.ClientController::getClientAction

##### OfferMatches routes #####
salesManagement.ClientMatches.get:
  methods: ['GET']
  path: clients/{clientId}/propertyMatches
  controller: SalesManagement.OfferMatchController::getPropertyMatchesForClient

### Filtering routes

salesManagement.Filter.addPropertySearchToClient:
  methods: ['POST']
  path: filters/client/add/{clientId}
  controller: SalesManagement.FilterController::addPropertySearchToClientAction

salesManagement.Filter.getClientFilters:
  methods: ['GET']
  path: filters/client/{clientId}
  controller: SalesManagement.FilterController::getClientFiltersAction

## Payments routes
userManagement.Payments.buyAccount:
  methods: ['GET']
  path: user/account/buy_account
  controller: UserManagement.PaymentProcessingController::buyAccountAction

