#index:
#    path: /
#    controller: App\Controller\DefaultController::index

## SalesManagement Routing

##### Offers Routes

## get all offers
salesManagement.getAllOffers:
  methods: ['GET']
  path: v1/offers
  controller: SalesManagement.OfferController::getAllOffersAction

salesManagement.addOffer:
  methods: ['POST']
  path: v1/offers
  controller: SalesManagement.OfferController::addOfferAction

salesManagement.getSingleOffer:
  methods: ['GET']
  path: v1/offers/{id}
  controller: SalesManagement.OfferController::getSingleOfferAction

##### Client routes

salesManagement.addClient:
  methods: ['POST']
  path: v1/clients
  controller: SalesManagement.ClientController::addClientAction

salesManagement.addProspectiveProperties:
  methods: ['POST']
  path: v1/clients/{clientId}/prospectiveProperties
  controller: SalesManagement.ClientController::addProspectivePropertyToClientAction

salesManagement.getClient:
  methods: ['GET']
  path: v1/clients/{id}
  controller: SalesManagement.ClientController::getClientAction

##### OfferMatches routes #####
salesManagement.ClientMatches.get:
  methods: ['GET']
  path: v1/clients/{clientId}/propertyMatches
  controller: SalesManagement.OfferMatchController::getPropertyMatchesForClient

### Filtering routes
salesManagement.Filter.addPropertySearchToClient:
  methods: ['POST']
  path: v1/client/{clientId}/filters
  controller: SalesManagement.FilterController::addPropertySearchToClientAction

salesManagement.Filter.getClientFilters:
  methods: ['GET']
  path: v1/client/{clientId}/filters
  controller: SalesManagement.FilterController::getClientFiltersAction

## Payments routes
userManagement.Payments.buyAccount:
  methods: ['GET']
  path: v1/user/account/buy_account
  controller: UserManagement.PaymentProcessingController::buyAccountAction

## Security
accountManagement.jwtCheck:
  path: v1/user/signin_check
  methods: ['POST']

gesdinet_jwt_refresh_token:
  path: v1/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

accountManagement.userRegistration:
  methods: ['POST']
  path: v1/user/signup
  controller: AccountManagement.UserRegistrationController:registerAccountAction


