parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false

    RealDeal\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    RealDeal\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    ### Shared ###

    realdeal.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    realdeal.encoder.xml:
        class: Symfony\Component\Serializer\Encoder\XmlEncoder

    realdeal.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
                - '@realdeal.salesmanagement.normalizer.client'
                - '@realdeal.salesmanagement.normalizer.offer_search'
                - '@serializer.normalizer.object'
            -
                - '@realdeal.encoder.json'
                - '@realdeal.encoder.xml'

    RealDeal.Api.ResponseBuilder:
        class: RealDeal\Shared\Infrastructure\ApiResponseBuilder
        arguments:
            - '@realdeal.serializer'

    ## queries ##
    RealDeal.Query.Elastic:
        class: RealDeal\Shared\Application\Query\ElasticQuery
        abstract: true
        calls:
            - [setContainer, ['@service_container']]

    ### SalesManagement ###

    ## repositories
    SalesManagement.Offer.OfferRepository:
        class: RealDeal\SalesManagement\Application\Repository\Offer\OfferRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    SalesManagement.Client.ClientRepository:
        class: RealDeal\SalesManagement\Application\Repository\Client\ClientRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    SalesManagement.Filter.OfferSearchRepository:
        class: RealDeal\SalesManagement\Application\Repository\Filter\OfferSearchRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    ## queries ##
    SalesManagement.Query.GetAllOffersQuery:
        class: RealDeal\SalesManagement\Application\Query\GetAllOffersQuery
        arguments:
            - '@service_container'
    SalesManagement.Query.GetSingleOfferQuery:
        class: RealDeal\SalesManagement\Application\Query\GetSingleOfferQuery
        arguments:
            - '@service_container'

    SalesManagement.Query.GetSingleClientQuery:
        class: RealDeal\SalesManagement\Application\Query\Client\GetSingleClientQuery
        arguments:
            - '@SalesManagement.Client.ClientRepository'

    SalesManagement.Query.Filter.GetClientFiltersQuery:
        class: RealDeal\SalesManagement\Application\Query\Filter\GetClientFilterQuery
        arguments:
            - '@SalesManagement.Filter.OfferSearchRepository'


    #command handlers
    SalesManagement.CommandHandler.CreateNewOffer:
        class: RealDeal\SalesManagement\Application\CommandHandler\CreateOfferHandler
        arguments:
            - '@SalesManagement.Offer.OfferFactory'
            - '@SalesManagement.Offer.OfferRepository'
            - '@SalesManagement.Client.ClientRepository'
            - '@messenger.bus.default'
            - '@service_container'
        tags:
            -
                name: messenger.message_handler
                handles: RealDeal\SalesManagement\Application\Command\CreateOfferCommand

    SalesManagement.CommandHandler.CreateNewClient:
        class: RealDeal\SalesManagement\Application\CommandHandler\Client\CreateClientCommandHandler
        arguments:
            - '@messenger.bus.default'
            - '@service_container'
            - '@SalesManagement.Client.ClientRepository'
        tags:
            - name: messenger.message_handler
              handles: RealDeal\SalesManagement\Application\Command\Client\CreateClientCommand

    SalesManagement.CommandHandler.AddProspectivePropertyToClient:
        class: RealDeal\SalesManagement\Application\CommandHandler\Client\AddProspectivePropertiesToClientCommandHandler
        arguments:
            - '@SalesManagement.Client.ClientRepository'
            - '@SalesManagement.Offer.OfferRepository'
        tags:
            - name: messenger.message_handler
              handles: RealDeal\SalesManagement\Application\Command\Client\AddProspectivePropertiesToClientCommand

    SalesManagement.CommandHandler.CreateNewClientLooksForPropertyFilterHandler:
        class: RealDeal\SalesManagement\Application\CommandHandler\Filter\CreateNewClientLooksForPropertyFilterHandler
        arguments:
            - '@SalesManagement.Client.ClientRepository'
            - '@SalesManagement.Filter.OfferSearchRepository'
            - '@messenger.bus.default'
        tags:
            - name: messenger.message_handler
              handles: RealDeal\SalesManagement\Application\Command\Filter\CreateNewClientLooksForPropertyFilterCommand

    #event handlers
    SalesManagement.EventHandler.OfferCreated:
        class: RealDeal\SalesManagement\Application\EventHandler\Offer\OfferCreatedHandler
        arguments:
            - '@service_container'
        tags:
            -
                name: messenger.message_handler
                handles: RealDeal\SalesManagement\Application\Event\Offer\OfferCreated

    SalesManagement.EventHandler.Client.NewClientCreatedHandler:
        class: RealDeal\SalesManagement\Application\EventHandler\Client\NewClientCreatedHandler
        arguments:
            - '@service_container'
        tags:
            -
                name: messenger.message_handler
                handles: RealDeal\SalesManagement\Application\Event\Client\ClientCreatedEvent

                ## controllers
    SalesManagement.OfferController:
        class: RealDeal\SalesManagement\Infrastructure\Controller\Offer\OfferController
        arguments:
            - '@messenger.bus.default'
            - '@RealDeal.Api.ResponseBuilder'
            - '@SalesManagement.Query.GetAllOffersQuery'
            - '@SalesManagement.Query.GetSingleOfferQuery'
        public: true
        tags: ['controller.service_arguments']

    SalesManagement.ClientController:
        class: RealDeal\SalesManagement\Infrastructure\Controller\Client\ClientController
        arguments:
            - '@messenger.bus.default'
            - '@RealDeal.Api.ResponseBuilder'
            - '@SalesManagement.Query.GetSingleClientQuery'
        public: true
        tags: ['controller.service_arguments']

    SalesManagement.FilterController:
        class: RealDeal\SalesManagement\Infrastructure\Controller\Filter\FilterController
        arguments:
            - '@messenger.bus.default'
            - '@RealDeal.Api.ResponseBuilder'
            - '@RealDeal\SalesManagement\Application\DomainService\Registry\Filter\Offer\OfferFilterFactoriesRegistry'
            - '@SalesManagement.Query.Filter.GetClientFiltersQuery'
        public: true
        tags: [ 'controller.service_arguments' ]

    ## normalizers

    realdeal.salesmanagement.normalizer.client:
        class: RealDeal\SalesManagement\Infrastructure\Serializer\Normalizer\Client\ClientNormalizer
        arguments:
            - '@router.default'
        tags:
            - { name: 'serializer.normalizer' }

    realdeal.salesmanagement.normalizer.offer_search:
        class: RealDeal\SalesManagement\Infrastructure\Serializer\Normalizer\Filter\OfferSearchNormalizer
        arguments:
            - '@router.default'
            - '@realdeal.salesmanagement.normalizer.client'
        tags:
            - { name: 'serializer.normalizer' }

    # domain services
    #factories
    SalesManagement.Offer.OfferFactory:
        class: RealDeal\SalesManagement\Application\DomainService\Offer\Factory\OfferFactory

    #### filters
    ### Offer (Property) filters
    RealDeal\SalesManagement\Application\DomainService\Registry\Filter\Offer\OfferFilterFactoriesRegistry: ~

    ## filter factories
    RealDeal\SalesManagement\Application\DomainService\Filter\Factory\OfferFilter\PriceRangeFilterFactory:
        tags:
            - { name: 'factory.filter.offer', filter_alias: 'price_range' }

    RealDeal\SalesManagement\Application\DomainService\Filter\Factory\OfferFilter\PropertyOfferingTypeFilterFactory:
        tags:
            - { name: 'factory.filter.offer', filter_alias: 'property_offering_type' }

    RealDeal\SalesManagement\Application\DomainService\Filter\Factory\OfferFilter\PropertyTypeFilterFactory:
        tags:
            - { name: 'factory.filter.offer', filter_alias: 'property_type' }

    RealDeal\SalesManagement\Application\DomainService\Filter\Factory\OfferFilter\RoomsNumberFilterFactory:
        tags:
            - { name: 'factory.filter.offer', filter_alias: 'rooms_number' }


