parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false

    RealDeal\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    RealDeal\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    
    ### Common ###
    commandBus:
        class: RealDeal\Shared\Infrastructure\CommandBus
        arguments: []
        calls:
            - [map, ['RealDeal\SalesManagement\Application\Command\CreateOfferCommand', '@SalesManagement.CommandHandler.CreateNewOffer']]
    
    ### SalesManagement ###
    ## repositories
    SalesManagement.Offer.OfferRepository:
        class: RealDeal\SalesManagement\Application\Repository\Offer\OfferRepository
        arguments:
            - '@doctrine.orm.entity_manager' 

    SalesManagement.Client.ClientRepository:
        class: RealDeal\SalesManagement\Application\Repository\Client\ClientRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    
    #command handlers
    SalesManagement.CommandHandler.CreateNewOffer:
        class: RealDeal\SalesManagement\Application\CommandHandler\CreateOfferHandler
        arguments: 
            - '@SalesManagement.Offer.OfferFactory'
            - '@doctrine.orm.entity_manager' 
            - '@event_dispatcher'  
            - '@service_container'
    
    #event handlers
            
    ## controllers
    SalesManagement.OfferController:
        class: RealDeal\SalesManagement\Infrastructure\Controller\Offer\OfferController
        arguments:
            - '@commandBus'
        public: true
        tags: ['controller.service_arguments']
    
    # domain services
    #factories
    SalesManagement.Offer.OfferFactory:
        class: RealDeal\SalesManagement\Application\DomainService\Offer\Factory\OfferFactory


            
        

