parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false

    RealDeal\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    RealDeal\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    ### SalesManagement ###
    ## repositories
    SalesManagement.Offer.OfferRepository:
        class: RealDeal\SalesManagement\Application\Repository\Offer\OfferRepository
        arguments:
            - '@doctrine.orm.entity_manager' 

    SalesManagement.Client.ClientRepository:
        class: RealDeal\SalesManagement\Application\Repository\Client\ClientRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    
    #command handlers
    SalesManagement.CommandHandler.CreateNewOffer:
        class: RealDeal\SalesManagement\Application\CommandHandler\CreateOfferHandler
        arguments: 
            - '@SalesManagement.Offer.OfferFactory'
            - '@SalesManagement.Offer.OfferRepository' 
            - '@messenger.bus.default'
            - '@service_container'
        tags:
            - 
                name: messenger.message_handler
                handles: RealDeal\SalesManagement\Application\Command\CreateOfferCommand
    
    #event handlers
    SalesManagement.EventHandler.OfferCreated:
        class: RealDeal\SalesManagement\Application\EventHandler\Offer\OfferCreatedHandler
        arguments:
            - '@service_container'
        tags:
            -   
                name: messenger.message_handler
                handles: RealDeal\SalesManagement\Application\Event\Offer\OfferCreated
                       
    ## controllers
    SalesManagement.OfferController:
        class: RealDeal\SalesManagement\Infrastructure\Controller\Offer\OfferController
        arguments:
            - '@messenger.bus.default'
        public: true
        tags: ['controller.service_arguments']
    
    # domain services
    #factories
    SalesManagement.Offer.OfferFactory:
        class: RealDeal\SalesManagement\Application\DomainService\Offer\Factory\OfferFactory


            
        

