export const ADD_NEW_OFFER = 'ADD_NEW_OFFER';
export const DELETE_OFFER = 'DELETE_OFFER';
export const FETCHING_OFFERS = 'FETCHING_OFFERS';
export const FETCHING_SINGLE_OFFER = 'FETCHING_SINGLE_OFFER';
export const LOAD_OFFERS_SUCCESS = 'LOAD_OFFERS_SUCCESS';
export const LOAD_OFFERS_FAILURE = 'LOAD_OFFERS_FAILURE';
