export const ADD_NEW_OFFER = 'ADD_NEW_OFFER';
export const DELETE_OFFER = 'DELETE_OFFER';
export const LOAD_OFFERS = 'LOAD_OFFERS';
export const LOAD_OFFERS_SUCCESS = 'LOAD_CLIENTS_SUCCESS';
export const LOAD_OFFERS_FAILURE = 'LOAD_CLIENTS_FAILURE';
